[project]
name = "resolve-robotics-uri-cpp"
# ignored, just added as it is compulsory
version = "0.0.0"
description = "Resolve a package:// or model:// URI to an absolute filename in C++."
authors = ["Silvio Traversaro <silvio.traversaro@iit.it>"]
channels = ["conda-forge","robotology","robostack-staging"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]

[tasks]

configure = { cmd = [
    "cmake",
    "-DCMAKE_BUILD_TYPE=Release",
    # Hack and workaround until CMake https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9200
    # is released, we use AMENT_PREFIX_PATH as it is defined thanks to ros-humble-moveit-resources-panda-description\
    # being installed, and it points to $CONDA_PREFIX on *nix and $CONDA_PREFIX\Library on Windows
    "-DCMAKE_INSTALL_PREFIX=$AMENT_PREFIX_PATH",
    "-DBUILD_TESTING:BOOL=ON",
    # Use the cross-platform Ninja generator
    "-G",
    "Ninja",
    # The source is in the root directory
    "-S",
    ".",
    # We wanna build in the .build directory
    "-B",
    ".build",
]}

build = { cmd = "cmake --build .build --config Release", depends-on = ["configure"] }
test = { cmd = "ctest --test-dir .build --build-config Release", depends-on = ["build"] }
install = { cmd = ["cmake", "--install", ".build", "--config", "Release"], depends-on = ["build"] }
uninstall = { cmd = ["cmake", "--build", ".build", "--target", "uninstall"]}
format = { cmd = "clang-format -i *.cpp *.h ./test/*.cpp" }


[dependencies]
pkg-config = "*"
make = "*"
cxx-compiler = "*"
cmake = "*"
ninja = "*"
catch2 = ">=3.5.2,<3.6"
clang-format = ">=17.0.6,<17.1"
# CI tests dependencies, not actualy dependencies
icub-models = "*"
ros-humble-moveit-resources-panda-description = "*"
