name: CI Workflow

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build-with-pixi:
    name: '[pixi:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        os: [ubuntu-22.04, macos-latest, windows-2019]

    steps:
    - uses: actions/checkout@v4

    - name: Print used environment (no conda) [Conda]
      shell: bash
      run: |
        env

    - uses: prefix-dev/setup-pixi@v0.5.1

    - name: Install the package
      shell: bash -l {0}
      run: pixi run install

    - name: Run the tests
      shell: bash -l {0}
      run: pixi run test

    # This test requires the conda-forge::icub-models,
    # robotology::ergocub-software and
    # robostack-staging::ros-humble-moveit-resources-panda-description
    # conda packages, that are installed in pixi environment
    - name: Check command line helper
      shell: bash -l {0}
      run: |
        resolve-robotics-uri-cpp package://iCub/robots/iCubGazeboV2_7/model.urdf
        resolve-robotics-uri-cpp package://ergoCub/robots/ergoCubSN000/model.urdf
        resolve-robotics-uri-cpp package://moveit_resources_panda_description/urdf/panda.urdf
        ! resolve-robotics-uri-cpp package://this/file/does/not/exist
